//#include "user.h"
//
//void testCode(void)
//{
//	printf("address of Kp: %p\n", Kp);
//	printf("address of Kd: %p\n\n", Kd);
//	Kp = m_constructor(NULL, NULL, 6, 0, 0, 0, 6, 0, 0, 0, 6);
//	printf("address of Kp: %p\n\n", Kp);
//	Kd = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	printf("address of Kp: %p\n", Kp);
//	printf("address of Kd: %p\n\n", Kd);
//	Matrix * Kd1 = m_constructor(NULL, NULL, 10.1, 0.2, 0.3, 0, 10, 0, 0, 0, 10);
//
//	printf("address of Kp: %p\n", Kp);
//	printf("address of Kd: %p\n", Kd);
//	printf("address of Kd1: %p\n\n", Kd1);
//	printf("pointerMatrix 0: %p\n", pointerMatrix[0]);
//	printf("pointerMatrix 1: %p\n", pointerMatrix[1]);
//	printf("pointerMatrix 2: %p\n", pointerMatrix[2]);
//	Matrix * Kd2 = m_constructor(NULL, NULL, 100.1, 101.2, 102.3, 0, 10, 0, 0, 0, 10);
//	printf("address of Kp: %p\n", Kp);
//	printf("address of Kd: %p\n", Kd);
//	printf("address of Kd1: %p\n", Kd1);
//	printf("address of Kd2: %p\n\n", Kd2);
//	Matrix * Kd3 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	printf("address of Kp: %p\n", Kp);
//	printf("address of Kd: %p\n", Kd);
//	printf("address of Kd1: %p\n", Kd1);
//	printf("address of Kd2: %p\n", Kd2);
//	printf("address of Kd3: %p\n\n", Kd3);
//	Matrix * Kd4 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	printf("address of Kp: %p\n", Kp);
//	printf("address of Kd: %p\n", Kd);
//	printf("address of Kd1: %p\n", Kd1);
//	printf("address of Kd2: %p\n", Kd2);
//	printf("address of Kd3: %p\n", Kd3);
//	printf("address of Kd4: %p\n\n", Kd4);
//	Matrix * Kd5 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	printf("address of Kp: %p\n", Kp);
//	printf("address of Kd: %p\n", Kd);
//	printf("address of Kd1: %p\n", Kd1);
//	printf("address of Kd2: %p\n", Kd2);
//	printf("address of Kd3: %p\n", Kd3);
//	printf("address of Kd4: %p\n", Kd4);
//	printf("address of Kd5: %p\n\n", Kd5);
//	Matrix * Kd6 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	printf("address of Kp: %p\n", Kp);
//	printf("address of Kd: %p\n", Kd);
//	printf("address of Kd1: %p\n", Kd1);
//	printf("address of Kd2: %p\n", Kd2);
//	printf("address of Kd3: %p\n", Kd3);
//	printf("address of Kd4: %p\n", Kd4);
//	printf("address of Kd5: %p\n", Kd5);
//	printf("address of Kd6: %p\n\n", Kd6);
//	Matrix * Kd1 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd2 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd3 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd4 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd5 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd6 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd7 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd8 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd9 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd10 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd11 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd12 = m_constructor(NULL, NULL, 10, 0, 0, 0, 10, 0, 0, 0, 10);
//	Matrix * Kd1 = (Matrix*)malloc(sizeof(Matrix));
//	Matrix * Kd2 = (Matrix*)malloc(sizeof(Matrix));
//	Matrix * Kd3 = (Matrix*)malloc(sizeof(Matrix));
//	Matrix * Kd4 = (Matrix*)malloc(sizeof(Matrix));
//	Matrix * Kd5 = (Matrix*)malloc(sizeof(Matrix));
//	Matrix * Kd6 = (Matrix*)malloc(sizeof(Matrix));
//	Matrix * Kd7 = (Matrix*)malloc(sizeof(Matrix));
//	Matrix * Kd8 = (Matrix*)malloc(sizeof(Matrix));
//	Matrix * Kd9 = (Matrix*)malloc(sizeof(Matrix));
//	Matrix * Kd10 = (Matrix*)malloc(sizeof(Matrix));
//	Matrix * Kd11 = (Matrix*)malloc(sizeof(Matrix));
//	Matrix * Kd12 = (Matrix*)malloc(sizeof(Matrix));
//	Vector3f* qd = v_constructor(NULL, 1, 2, 3);
//	Vector3f* dqd = v_constructor(NULL, 4, 5, 6);
//	Vector3f* ddqd = v_constructor(NULL, 2, 3, 4);
//	Vector3f* q = v_constructor(NULL, 5, 6, 7);
//	Vector3f* dq = v_constructor(NULL, 1, 5, 9);
//}